Feature/user role queries
BobaBoard/boba-backend pull request #125
Opened 2023-03-13 00:34 UTC by mindthespines

Addresses [issue #136](https://github.com/BobaBoard/issues/issues/136)

- Adds tested queries for:
    - Getting all user roles in the realm
    - Getting all user roles on a particular board

Wasn't sure if we actually needed the breakdown by board for purposes of this issue, but thought it might be useful.

2023-03-13 00:44 UTC, mindthespines commented
I have a sneaking suspicion that something is wrong with how I'm doing the all roles query - if I haven't updated this by the time you're reviewing give me a yell!

2023-03-13 02:57 UTC, mindthespines commented
I think I may need to keep tweaking the realm roles query, since it looks like we'll want to know the board associated with each role, so one more table to check! Will likely add this tomorrow.

2023-03-17 02:47 UTC, essential-randomness requested changes
Just the comment about indentation, unless you want to do changes to have the assigned boards in this PR.

I think roles should have either a `realms` properties and a `boards` properties which contain arrays of the IDs of where those roles are available (empty by default, rather than null).

2023-03-17 02:47 UTC, essential-randomness commented on server/users/sql/index.ts
> +SELECT roles.*
Indentation here :)

We don't have set rules but I generally try to indent the  `ON` and `AND` in the SQL, and the baseline of the query itself is also indented (as you can see above).

2023-03-18 19:07 UTC, mindthespines commented
Still working on updating the query, this will probably update a few times throughout the day

2023-04-06 00:37 UTC, mindthespines commented
I combined it all into one big query that will return everything the endpoint will be aiming to surface, let me know if there's anything to change! There will need to be some small additional queries added (like getting the accessory details) when I'm working on the API but I think for those it would be better to write them as I see what I'm grabbing for to send the role info. I'm cool with calling this PR done if it looks solid, then making changes on the next one as needed.

2023-04-08 21:56 UTC, mindthespines commented
Changed it again after starting on the API ticket and realizing we only want to get the roles per realm - that's the last unprompted change for real this time 😅

2023-05-05 20:02 UTC, essential-randomness approved these changes

2023-05-19 21:33 UTC, merged